name: DRONE REMOTE

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
  create:
    tags:
      - 'v*'

jobs:
  android-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Create zip archive
          run: |
            zip -r release.zip .
        
        - name: Upload release.zip as artifact
          uses: actions/upload-artifact@v2
          with:
            name: release-artifact
            path: release.zip
