name: DRONE REMOTE

on:

  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
  create:
    tags:
      - 'v*'

        
        
jobs:
  android-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and deploy Android app
        run: |
          cd kivi_app

          # Build and deploy the app using Buildozer
          buildozer android debug deploy run --name "drone_remote_controller"

          # Install the APK on the emulator
          adb install bin/drone_remote_controller-debug.apk

      - name: Move APK to release folder
        run: |
          mkdir -p release
          mv kivi_app/bin/drone_remote_controller-debug.apk release/drone_remote_controller-debug.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: release/drone_remote_controller-debug.apk
